
[I 2023-06-16 10:40:16,610] A new study created in memory with name: no-name-a987779c-5ca4-4309-a70e-af808b45ee0e
c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
[I 2023-06-16 11:03:13,995] Trial 0 finished with value: 0.8346666693687439 and parameters: {'learning_rate': 0.01820689840908506}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 14:58:06,991] Trial 1 finished with value: 0.8291666507720947 and parameters: {'learning_rate': 0.013396849444523675}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 16:05:10,075] Trial 2 finished with value: 0.8340833187103271 and parameters: {'learning_rate': 0.013812013637608835}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 17:37:58,451] Trial 3 finished with value: 0.2684166729450226 and parameters: {'learning_rate': 1.0073203491515725e-05}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 18:57:44,727] Trial 4 finished with value: 0.7744166851043701 and parameters: {'learning_rate': 0.0021969522161881454}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 19:27:33,322] Trial 5 finished with value: 0.5143333077430725 and parameters: {'learning_rate': 0.00011417469965512124}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 19:47:37,716] Trial 6 finished with value: 0.8267499804496765 and parameters: {'learning_rate': 0.08425014629427345}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 20:06:28,240] Trial 7 finished with value: 0.6485833525657654 and parameters: {'learning_rate': 0.0004782617362871087}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 20:32:42,492] Trial 8 finished with value: 0.8019999861717224 and parameters: {'learning_rate': 0.004506029175514268}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 21:03:26,839] Trial 9 finished with value: 0.47841668128967285 and parameters: {'learning_rate': 7.422018058015538e-05}. Best is trial 0 with value: 0.8346666693687439.
[I 2023-06-16 21:25:27,515] Trial 10 finished with value: 0.8356666564941406 and parameters: {'learning_rate': 0.06051531714605409}. Best is trial 10 with value: 0.8356666564941406.
[W 2023-06-16 21:26:03,511] Trial 11 failed with parameters: {'learning_rate': 0.048803762742084145} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\caiay\AppData\Local\Temp\ipykernel_8416\1417286301.py", line 32, in objective
    model.fine_tune(3, base_lr = learning_rate)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\callback\schedule.py", line 165, in fine_tune
    self.fit_one_cycle(freeze_epochs, slice(base_lr), pct_start=0.99, **kwargs)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\callback\schedule.py", line 119, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd, start_epoch=start_epoch)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 264, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 253, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 247, in _do_epoch
    self._do_epoch_train()
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 239, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\learner.py", line 205, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\load.py", line 127, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\load.py", line 138, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\basics.py", line 230, in chunked
    res = list(itertools.islice(it, chunk_sz))
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\load.py", line 153, in do_item
    try: return self.after_item(self.create_item(s))
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\load.py", line 160, in create_item
    if self.indexed: return self.dataset[s or 0]
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\core.py", line 458, in __getitem__
    res = tuple([tl[it] for tl in self.tls])
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\core.py", line 458, in <listcomp>
    res = tuple([tl[it] for tl in self.tls])
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\core.py", line 417, in __getitem__
    return self._after_item(res) if is_indexer(idx) else res.map(self._after_item)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\data\core.py", line 377, in _after_item
    def _after_item(self, o): return self.tfms(o)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\transform.py", line 208, in __call__
    def __call__(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\transform.py", line 158, in compose_tfms
    x = f(x, **kwargs)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\transform.py", line 81, in __call__
    def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\transform.py", line 91, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\transform.py", line 97, in _do_call
    return retain_type(f(x, **kwargs), x, ret)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastcore\dispatch.py", line 120, in __call__
    return f(*args, **kwargs)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\vision\core.py", line 125, in create
    return cls(load_image(fn, **merge(cls._open_args, kwargs)))
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\vision\core.py", line 98, in load_image
    im = Image.open(fn)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3231, in open
    filename = str(fp.resolve())
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1077, in resolve
    s = self._accessor.realpath(self, strict=strict)
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 686, in realpath
    path = _getfinalpathname(path)
KeyboardInterrupt
[W 2023-06-16 21:26:03,551] Trial 11 failed with value None.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: optuna in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (1.11.1)
Requirement already satisfied: cmaes>=0.9.1 in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (0.9.1)
Requirement already satisfied: colorlog in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (6.7.0)
Requirement already satisfied: numpy in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (1.24.3)
Requirement already satisfied: packaging>=20.0 in c:\users\caiay\appdata\roaming\python\python310\site-packages (from optuna) (23.1)
Requirement already satisfied: sqlalchemy>=1.3.0 in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (2.0.16)
Requirement already satisfied: tqdm in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (4.65.0)
Requirement already satisfied: PyYAML in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from optuna) (6.0)
Requirement already satisfied: Mako in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna) (1.2.4)
Requirement already satisfied: typing-extensions>=4 in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna) (4.6.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy>=1.3.0->optuna) (2.0.2)
Requirement already satisfied: colorama in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\caiay\appdata\local\programs\python\python310\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)